name: Flake8 Runner

on: [push]

jobs:
  lint:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tonybajan/flake8-check-action@v1.0.0
      with:
        select: E3,E4,E5,E7,W6,F,B,G0
        ignore: E203, E266, W5013
        maxlinelength: 119
        repotoken: ${{ secrets.GITHUB_TOKEN }}
